### PR TITLE
Fixes screen width for add issue dialog (fix #37)

### LINKED ISSUE #37: Add issue component's width increases as we enter more text.
cynthesize-issue

### PR DESCRIPTION
**Pull request by thesmallstar**
fixes #37 

changes Referred from https://github.com/sparksuite/simplemde-markdown-editor

angular_1

I hope this is all correct :)

### CODE REVIEW

**Comment by thesmallstar** [comment]
In the last commit  I didnot consider the mobile view, where the width cannot be always 500px it will be a mess. Hence the max-width property is better suited here. I properly aligned the boxes :)

**Comment by WickedBrat1** [comment]
@thesmallstar thanks for the PR! Looks good to me but I think it'll be better to have the width of the Dialog to be at least 50% of the screen width for desktop browsers

**Comment by thesmallstar** [comment]
@WickedBrat1  Okay, I am working on it :)

**Comment by thesmallstar** [comment]
@WickedBrat1  
I have added 50% width for all Desktop devices. 
I tested the same with all mobile devices and Ipad sizes using chrome-dev. Works great. 
please review this :)

**Comment by WickedBrat1** [comment]
Looks good to me! @thesmallstar

**Pull request merged**
