### PR TITLE
User page designed

### PR DESCRIPTION
**Pull request by zerefwayne**
Contributions section yet to be decided upon.

### Screenshots

image
image
image
image
image

### CODE REVIEW

**Comment by WickedBrat1** [comment]
Looks good to me

**Comment by WickedBrat1** [comment]
@zerefwayne Is this the final color combination that'll be used?

**Comment by zerefwayne** [comment]
Yeah I have mentioned the colors in sass/variables.scss

**Comment by WickedBrat1** [comment]
No, I meant with consistency of the UI. Also, instead of importing SVG icons, wouldn't it be better if we used font-awesome icons?

**Comment by zerefwayne** [comment]
@WickedBrat1 Font icons may cause problems if the device doesn't recognize it or has some problems rendering it. SVGs are the safest to use imo.

**Comment by WickedBrat1** [comment]
cool :+1:

**Pull request merged**
